[project]
name = "exercise1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kkkvvvnn", email = "kevin931015@gmial.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
exercise1 = "exercise1:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
